- hosts: localhost
  become: true
  tasks:
  - name: install vscode snap with option --classic
    snap: 
      name: code
      classic: yes
  - name: Run the equivalent of "apt-get update" as a separate step
    apt:
      update_cache: yes
  - name: install python-related packages
    apt: 
      name: ['python3-pip', 'pipenv']
  - name: Upgrade all packages to the latest version
    apt:
      name: "*"
      state: latest
  - name: Update all packages to the latest version
    apt:
      upgrade: dist
  - name: Remove useless packages from the cache
    apt:
      autoclean: yes
  - name: Remove dependencies that are no longer required
    apt:
      autoremove: yes
  