- hosts: localhost
  become: true
  tasks:
  - name: install vscode snap with option --classic
    snap: 
      name: code
      classic: yes
  - name: install python-related packages
    apt: name=['python3-pip', 'pipenv']
